// seed/vehicleData.js
module.exports = [
  {
    vin: '5YJ3E1EA7KF317XXX',
    make: 'Tesla',
    model: 'Model 3',
    year: 2023,
    type: 'Electric',
    pricePerDay: 79,
    imageUrl: '/images/tesla.jpg',
    description: 'Smooth ride, fully electric, smart features.',
    seats: 5,
    mpg: '130 MPGe',
    isFeatured: true,
    available: true
  },
  {
    vin: 'JTMWFREV0JJ123XXX',
    make: 'Toyota',
    model: 'RAV4',
    year: 2022,
    type: 'Hybrid',
    pricePerDay: 52,
    imageUrl: '/images/rav4.jpg',
    description: 'Reliable and efficient SUV.',
    seats: 5,
    mpg: '40 MPG',
    isFeatured: true,
    available: true
  },
  {
    vin: '1FA6P8TH0L5104XXX',
    make: 'Ford',
    model: 'Mustang',
    year: 2021,
    type: 'Sport',
    pricePerDay: 89,
    imageUrl: '/images/mustang.jpg',
    description: 'Classic American muscle car.',
    seats: 4,
    mpg: '25 MPG',
    isFeatured: true,
    available: true
  },
  {
    vin: '3N1AB7AP4KY256789',
    make: 'Nissan',
    model: 'Sentra',
    year: 2020,
    type: 'Sedan',
    pricePerDay: 39,
    imageUrl: '/images/nissan-sentra.jpg',
    description: 'Compact and fuel-efficient, ideal for city driving.',
    seats: 5,
    mpg: '33 MPG',
    isFeatured: false,
    available: true
  },
  {
    vin: '1HGCV1F34LA023456',
    make: 'Honda',
    model: 'Accord',
    year: 2021,
    type: 'Sedan',
    pricePerDay: 48,
    imageUrl: '/images/honda-accord.jpg',
    description: 'Spacious, smooth ride, and great for families.',
    seats: 5,
    mpg: '31 MPG',
    isFeatured: false,
    available: true
  },
  {
    vin: '5XYKTCA23FG543210',
    make: 'Kia',
    model: 'Sorento',
    year: 2022,
    type: 'SUV',
    pricePerDay: 55,
    imageUrl: '/images/kia-sorento.jpg',
    description: 'Great for road trips and cargo space.',
    seats: 7,
    mpg: '29 MPG',
    isFeatured: false,
    available: true
  },
  {
    vin: '2T3ZFREV1KW015789',
    make: 'Toyota',
    model: 'Highlander',
    year: 2023,
    type: 'SUV',
    pricePerDay: 67,
    imageUrl: '/images/toyota-highlander.jpg',
    description: 'Spacious, reliable and family-friendly SUV.',
    seats: 8,
    mpg: '28 MPG',
    isFeatured: true,
    available: true
  },
  {
    vin: '1C4RJFBG7LC123456',
    make: 'Jeep',
    model: 'Grand Cherokee',
    year: 2021,
    type: '4x4',
    pricePerDay: 64,
    imageUrl: '/images/jeep-grandcherokee.jpg',
    description: 'Rugged design for all-terrain adventures.',
    seats: 5,
    mpg: '22 MPG',
    isFeatured: false,
    available: false
  },
  {
    vin: '3FA6P0G73HR256111',
    make: 'Ford',
    model: 'Fusion',
    year: 2020,
    type: 'Sedan',
    pricePerDay: 42,
    imageUrl: '/images/ford-fusion.jpg',
    description: 'Comfortable mid-size sedan with smooth handling.',
    seats: 5,
    mpg: '27 MPG',
    isFeatured: false,
    available: true
  },
  {
    vin: 'WBA8E9G58GNU02000',
    make: 'BMW',
    model: '328i',
    year: 2019,
    type: 'Luxury',
    pricePerDay: 85,
    imageUrl: '/images/bmw-328i.jpg',
    description: 'Sporty luxury sedan with premium features.',
    seats: 5,
    mpg: '26 MPG',
    isFeatured: true,
    available: false
  },
  {
    vin: '5UXTR7C59KLD88990',
    make: 'BMW',
    model: 'X3',
    year: 2022,
    type: 'SUV',
    pricePerDay: 92,
    imageUrl: '/images/bmw-x3.jpg',
    description: 'Luxury crossover with advanced tech and comfort.',
    seats: 5,
    mpg: '25 MPG',
    isFeatured: true,
    available: true
  },
  {
    vin: '1FTFW1E51KFC87432',
    make: 'Ford',
    model: 'F-150',
    year: 2022,
    type: 'Truck',
    pricePerDay: 77,
    imageUrl: '/images/ford-f150.jpg',
    description: 'America’s favorite truck. Durable and reliable.',
    seats: 5,
    mpg: '20 MPG',
    isFeatured: false,
    available: true
  },
  {
    vin: '5YJSA1E26HF236789',
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    type: 'Electric',
    pricePerDay: 110,
    imageUrl: '/images/tesla-models.jpg',
    description: 'High-performance electric sedan with long range.',
    seats: 5,
    mpg: '120 MPGe',
    isFeatured: true,
    available: true
  }
];
